#!/usr/bin/env bash

rosdep install --from-paths src --ignore-src -r -y &&
git submodule update --init --recursive 

DESCRIPTIONS_PATH=$(dirname "$(realpath $0)")/src/robots/descriptions

mkdir -p $DESCRIPTIONS_PATH
cd $DESCRIPTIONS_PATH
git clone -b gazebo https://github.com/chvmp/spot_ros

cd $DESCRIPTIONS_PATH/../../..

catkin_make